sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - cd docs
  - doxygen Doxyfile

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/html
  github-token: $GH_REPO_TOKEN
  on:
    branch: master