sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - doxygen Doxyfile

before_install:
    - sudo apt-get install python-software-properties
    - sudo apt-add-repository -y ppa:libreoffice/libreoffice-4-2
    - sudo apt-get update
    - sudo apt-get install doxygen
    
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
