sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - doxygen Doxyfile

before_install:
- cd ${TMPDIR-/tmp}
- curl ${DOXYGEN_URL} -o doxygen.tar.gz
- tar zxvf doxygen.tar.gz
- mkdir doxygen_build
- cd doxygen_build
- cmake ../doxygen-Release_1_8_17/
- make
- export PATH="${TMPDIR-/tmp}/doxygen_build/bin:$PATH"
- cd ../../
- cd "${TRAVIS_BUILD_DIR}";
- doxygen ${TRAVIS_BUILD_DIR}/build/doc/Doxyfile;
- doxygen ${TRAVIS_BUILD_DIR}/build/doc/Doxyfile.zh-cn;

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
