sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - doxygen Doxyfile

before_install:
- cd ${TMPDIR-/tmp}
- curl https://codeload.github.com/doxygen/doxygen/tar.gz/Release_1_8_17 -o doxygen.tar.gz
- tar zxvf doxygen.tar.gz
- mkdir doxygen_build
- cd doxygen_build
- cmake ../doxygen-Release_1_8_17/
- make
- export PATH="${TMPDIR-/tmp}/doxygen_build/bin:$PATH"
- cd ${TMPDIR-/tmp}
- curl https://graphviz.gitlab.io/pub/graphviz/stable/SOURCES/graphviz.tar.gz -o graphviz-2.40.1.tar.gz
- zcat graphviz-2.40.1.tar.gz | tar xfvo -
- cd graphviz-2.40.1
- ./configure
- make
- sudo make install
- cd ../../
- cd "${TRAVIS_BUILD_DIR}";

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
